### ISSUE TITLE
v10 Docs

### ISSUE THREAD

**Issue by reconbot** [serialport/website#71]
What needs to be updated for v10 docs, feel free to edit this issue or comment to add notes or tasks

## Todo 
- [x] put the upgrade guide somewhere - maybe move it from the repo?
- [x] Decide if we're going to use require or import for all examples
### Getting Started
- [x] About SerialPort
  - [x] guide-about.md has [parser names not package names](https://serialport.io/docs/next/#parser-packages) 
- [x] Supported Environments
- [x] Installing SerialPort
### Guides
- [x] SerialPort Usage
- [x] Electron
- [x] Debugging
- [x] Error Handling
- [x] Testing
### Core Packages
- [x] What are core packages?
- [x] 📦 serialport
- [x] 📦 @serialport/stream
- [x] 📦 @serialport/bindings-cpp
- [x] 📦 @serialport/binding-mock
- [x] [📦 @serialport/bindings-interface](https://github.com/serialport/website/pull/73)
### Parser Packages
- [x] What are Parsers?
- [x] 📦 ByteLength Parser
- [x] 📦 ccTalk Parser
- [x] 📦 Delimiter Parser
- [x] 📦 InterByteTimeout Parser
- [x] 📦 PacketLengthParser https://github.com/serialport/website/pull/75
- [x] 📦 Readline Parser
- [x] 📦 Ready Parser
- [x] 📦 Regex Parser
- [x] 📦 Slip Encoder Parser
- [x] 📦 Space Packet Parser https://github.com/serialport/website/pull/75
### Command Line Packages
- [x] 📦 @serialport/list
- [x] 📦 @serialport/terminal
- [x] 📦 @serialport/repl
### Community
- [x] Code of Conduct

**Comment by reconbot** [comment]
Overall I think we're in a good place. Please open PRs for any adjustments and suggestions.
